services:
  - type: web
    name: airline-backend
    runtime: docker
    branch: main
    dockerfilePath: Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: airline-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: airline-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: airline-db
          property: password
      - key: DATABASE_DRIVER
        value: org.postgresql.Driver
      - key: JPA_DDL_AUTO
        value: update
      - key: SPRING_PROFILES_ACTIVE
        value: google
      - key: GOOGLE_AUTH_ENABLED
        value: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BACKEND_URL
        value: https://airline-reservation-system-2t4j.onrender.com
      - key: GOOGLE_REDIRECT_URI
        value: https://airline-reservation-system-2t4j.onrender.com/login/oauth2/code/google
      - key: FRONTEND_URL
        sync: false


databases:
  - name: airline-db
    plan: free
    databaseName: airline_db
    user: airline_user
