FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn -q clean package -DskipTests

FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /build/target/*.jar app.jar
EXPOSE 8080
ENV PORT=8080
ENV JAVA_TOOL_OPTIONS="-Xmx512m -Xms256m"
CMD ["java", "-jar", "app.jar"]
